### ISSUE TITLE
Menu failing to show properly on edge of screen | Moodle 2.8.2+

### ISSUE THREAD

**Issue by derekc** [CTANZ/moodle-theme_decaf#17]
I am sure this is a regression.  :-)  I don't think it used to do this.
![image](https://cloud.githubusercontent.com/assets/687780/6205715/548086bc-b5dd-11e4-856b-cb5050a3ee97.png)

**Comment by pauln** [comment]
I can't see any sign of a workaround for this within the responsive branch or the original branch.  If you can find evidence of a previous version doing something about it, please provide a screenshot and version numbers for both Decaf and Moodle, and I'll see if I can bring it back.

There's a reasonably narrow range of browser window widths at which you'll experience cut-off like that, and typically only if you are an administrator and viewing a page within a module context (so you have module admin, course admin and site admin menus all visible).

If you're unable to make your browser window any wider (due to using a monitor which falls just within the aforementioned range), you can either make your browser window narrower until you get the mobile interface and can use the touch-mode Awesomebar (which isn't brilliant with a mouse, unfortunately) or tweak some of the language strings to make them narrower (core moodle.php "courseadministration" plus the "pluginadministration" string within each activity/resource module that's long enough to cause problems).  You could simply shorten them to "[type] admin" which, between course and activity/resource, might save you enough space to fit the rest of the menu in (based on your screenshot).  If not, you could also adjust others, such as "myprofile" (moodle.php).

**Comment by derekc** [comment]
OK.  I've done all you suggest Paul, thanks.
Sadly I have NO old versions of Decaf + Moodle to see if the behaviour is my imagination or real.  My memory was that the menus went to the left.  :-)

Retire this issue.  Thanks.
