### ISSUE TITLE
Horizontal scrolling in attendance module

### ISSUE THREAD

**Issue by derekc** [CTANZ/moodle-theme_decaf#18]
My worst nightmare.  Two plugins that don't play nicely together.
WITH CLEAN THEME:
![image](https://cloud.githubusercontent.com/assets/687780/6660245/28fcbec4-cbfa-11e4-87f5-061e88b7a140.png)
WITH DECAF:
![image](https://cloud.githubusercontent.com/assets/687780/6660248/33d00248-cbfa-11e4-844d-5e1972cd22c7.png)
ie, the vertical scrolling bar is not there in decaf.

-Derek

**Comment by derekc** [comment]
Using 2.8.2+
Using Chrome
WITH CLEAN, there is NO truncation of the table in reports:
![image](https://cloud.githubusercontent.com/assets/687780/6660276/b53df1d2-cbfa-11e4-9049-7e1554efaa42.png)
WITH DECAF: there is truncation:
![image](https://cloud.githubusercontent.com/assets/687780/6660278/c54810a8-cbfa-11e4-9226-e761dec749b5.png)

-Derek

**Comment by derekc** [comment]
We may have got a CSS fix for this.  Let me know if you are interested.

-Derek

**Comment by pauln** [comment]
This is fixed in 2.0.7 (which will be released in the Moodle plugins database shortly).  Note that, as per the non-responsive version of Decaf for older Moodle versions, the horizontal scrollbar will be at the bottom of the report - only the page content area scrolls, not the header etc - but you can use the middle mouse button or other scrolling methods to scroll the report without needing to see the horizontal scrollbar.
