### ISSUE TITLE
Arrows missing on Assignment grading screen

### ISSUE THREAD

**Issue by Tigger996** [CTANZ/moodle-theme_decaf#27]
In the Clean theme:
![grader-arrows-clean](https://cloud.githubusercontent.com/assets/4732329/18521295/5b5b26b0-7a60-11e6-8c64-cff8839a95df.png)
In Decaf:
![grader-arrows-decaf](https://cloud.githubusercontent.com/assets/4732329/18521361/a60886b2-7a60-11e6-984c-450bf4fb5a29.png)

In the Clean theme, the generated code is:
`<a data-action="next-user" href="#next">►</a>
`
However, when using Decaf:
`<a data-action="next-user" href="#next"> </a>`

As you can see the arrows are missing on the grading screen for assignments.  Can this be fixed easily?

**Comment by pauln** [comment]
Fixed in 2.1.1 - thanks for reporting!

These arrows were "blanked out" in Decaf some time ago in order to style them differently in section headers, but that's now possible without obliterating them from all places where they should be.  2.1.1 consequently has left/right arrows in several other places too - wherever other themes normally display them.

**Comment by Tigger996** [comment]
Where can I get 2.1.1?

**Comment by Tigger996** [comment]
Thanks for fixing so fast. I see the report links in the profile have been fixed as well.  I have my own themes that inherit from decaf, but the arrows don't show in my inherited themes.  What do I do to fix that?

Thanks!

**Comment by Tigger996** [comment]
Thanks for fixing so quickly!  ALL works great now :)

Lori
