### ISSUE TITLE
Moodle 3.6.1 issues

### ISSUE THREAD

**Issue by Tigger996** [CTANZ/moodle-theme_decaf#32]
Since the upgrade, I now have a scroll bar along the bottom (never had that before)  which I think might have to do with the new messaging UI or my custom adjustments though as when I use Decaf on its own (my theme inherits decaf) there is no horizontal scroll bar at the bottom of the browser.  

However,  when messages are opened, the box to enter messages is partially cut off.

Thanks.
![screenshot-messages-2019-01-098](https://user-images.githubusercontent.com/4732329/50931652-1a07cc00-1418-11e9-8ca0-9c58364e96cc.png)

**Comment by pauln** [comment]
I haven't seen any (unexpected) horizontal scrollbars during my testing, so it seems most likely that it's the result of some combination of your child theme's styles and the new messaging UI.  If your child theme is publicly available somewhere, I might be able to have a quick look if you're unable to figure out where the scrollbar's coming from - but if not, there isn't much I can do since it doesn't seem to be able to be reproduced using Decaf.

As for the messaging UI being cut off, I've just released v2.3.1 which fixes that issue - thanks for reporting it!

**Comment by Tigger996** [comment]
So the horizontal bar was with my custom theme changes.  So I've managed to fix that.

Messages look good now. 

My only recommendations (non-critical) would be that since messages pop-out in a drawer now, to remove the messages link in the user dropdown (where users access their dashboard/profile etc), as going to the messages page now seems pointless.  But I guess it's needed in older versions.  So unless you can display based on Moodle version, I guess it needs to say :)

Thanks for all the quick responses.  I really appreciate it.
