### ISSUE TITLE
missing privacy api

### ISSUE THREAD

**Issue by danmarsden** [CTANZ/moodle-theme_decaf#33]
Hey Paul - I see you've created a new version of this for 3.5/3.6 but the privacy api class is missing - Moodle has some unit tests that check for the privacy api in all plugins so sites using Continuous Integration will see unit test failures with this plugin in place. You can use the null provider class as your plugin doesn't store any user data.
more info on the privacy api is here:
https://docs.moodle.org/dev/Privacy_API

**Comment by pauln** [comment]
Hi Dan,
Thanks for this (and the PR) - I unfortunately haven't been managing to keep up with Moodle happenings since leaving UC, so I hadn't picked up on the need for a privacy provider.  At a glance, it appears that the Privacy API was introduced in Moodle 3.3; is there any reason that your PR wouldn't work on 3.3 or 3.4 (or, for that matter, 3.1/3.2 - given that the implementation is a new file (and string))?  I'm just wondering whether I need to adjust the version compatibility on a new release which includes the privacy provider (per your PR)...

**Comment by danmarsden** [comment]
yeah good question - I've sent you a pull request for the 3.4 and higher privacy class (PHP 7), but because you are supporting 3.3 in your plugin (PHP 5.6) it probably needs to use the polyfill like the one in this plugin:
https://github.com/catalyst/moodle-tool_lockstats/blob/master/classes/privacy/provider.php
Docs here:
https://docs.moodle.org/dev/Privacy_API#What_to_do_if_you_have_one_plugin_that_supports_multiple_branches

having the class in place for older releases (3.2 and lower) doesn't matter because it doesn't get used by anything.

I'll see if I can get some time to fix that pull request up and include the polyfill sometime tomorrow - unless you just want to branch it and "drop" support for older releases in your current branch.

thanks,

**Comment by pauln** [comment]
Thanks, Dan - if you do get a chance to update the PR tomorrow, that'd be great!

**Comment by danmarsden** [comment]
updated to use the polyfill class - thanks!

**Comment by pauln** [comment]
Thanks, Dan - I've just released v2.3.2, which includes both this and your custom menu PR.
