### ISSUE TITLE
awesome-bar problem in decaf, krystle and Halboo with moodle 2.6: 'Unknown Type' generalexceptionmessage 

### ISSUE THREAD

**Issue by actXc** [CTANZ/moodle-theme_decaf#6]
can you help?

https://moodle.org/mod/forum/discuss.php?d=244270#p1059122

**Comment by pauln** [comment]
This has been fixed in v1.9.0RC1 - please test and provide feedback in the Moodle.org forum discussion linked above.  As per my comment there, this is an interim release for those who can't wait until I find the time to do a full Moodle 2.6 version of Decaf, so it's not perfect - but it addresses the major 2.6 compatibility issues (that I'm aware of).
